version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  scheduler:
    image: apache/airflow:latest
    command: scheduler
    depends_on:
      - postgres
    restart: on-failure:3
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
  webserver:
    image: apache/airflow:latest
    entrypoint: ./scripts/entrypoint.sh
    depends_on:
      - postgres
      - scheduler
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    ports:
      - "9000:8080"